# Generated by Django 2.0.5 on 2018-09-27 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='新笔记', max_length=100, verbose_name='标题')),
                ('content', models.TextField(blank=True, default='', verbose_name='内容')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_archived', models.BooleanField(default=False, verbose_name='是否归档')),
                ('cover', models.TextField(blank=True, default='', verbose_name='封面')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'NoteBook',
                'ordering': ('update_datetime',),
            },
        ),
        migrations.AddField(
            model_name='note',
            name='render_type',
            field=models.IntegerField(choices=[(0, '不渲染'), (1, 'Markdown 渲染')], default=1, verbose_name='渲染类型'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, default='新笔记', max_length=100, verbose_name='标题'),
        ),
        migrations.AlterModelTable(
            name='note',
            table='Notes',
        ),
        migrations.AddField(
            model_name='note',
            name='notebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.NoteBook', verbose_name='笔记本'),
        ),
    ]
