# Generated by Django 2.0.5 on 2018-09-12 13:54

import apps.schedules.models
from django.db import migrations, models
import enumfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='新任务', max_length=100, verbose_name='标题')),
                ('content', models.TextField(blank=True, default='', verbose_name='内容')),
                ('label', enumfields.fields.EnumIntegerField(default=0, enum=apps.schedules.models.Label, verbose_name='重要紧急标签')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_archived', models.BooleanField(default=False, verbose_name='是否归档')),
                ('is_finished', models.BooleanField(default=False, verbose_name='是否完成')),
                ('finished_datetime', models.DateTimeField(default=None, null=True, verbose_name='完成时间')),
                ('is_all_day', models.BooleanField(default=True, verbose_name='是否全天')),
                ('begin_datetime', models.DateTimeField(default=None, null=True, verbose_name='开始时间')),
                ('end_datetime', models.DateTimeField(default=None, null=True, verbose_name='结束时间')),
            ],
            options={
                'ordering': ('update_datetime',),
                'db_table': 'schedules',
            },
        ),
    ]
