# Generated by Django 2.0.5 on 2018-09-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='begin_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='finished_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='完成时间'),
        ),
    ]
