# Generated by Django 2.0.5 on 2018-09-27 03:39

import apps.schedules.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0003_auto_20180913_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='新任务', max_length=100, verbose_name='标题')),
                ('content', models.TextField(blank=True, default='', verbose_name='内容')),
                ('label', enumfields.fields.EnumIntegerField(default=0, enum=apps.schedules.models.Label, verbose_name='重要紧急标签')),
                ('cover', models.TextField(blank=True, default='', verbose_name='封面')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_archived', models.BooleanField(default=False, verbose_name='是否归档')),
                ('is_star', models.BooleanField(default=False, verbose_name='是否星标')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'Plans',
                'ordering': ('update_datetime',),
            },
        ),
        migrations.CreateModel(
            name='SubPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='新任务', max_length=100, verbose_name='标题')),
                ('content', models.TextField(blank=True, default='', verbose_name='内容')),
                ('label', enumfields.fields.EnumIntegerField(default=0, enum=apps.schedules.models.Label, verbose_name='重要紧急标签')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_archived', models.BooleanField(default=False, verbose_name='是否归档')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Plan', verbose_name='计划')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'SubPlans',
                'ordering': ('update_datetime',),
            },
        ),
        migrations.AddField(
            model_name='task',
            name='rawtext',
            field=models.BooleanField(default=True, verbose_name='是否纯文本'),
        ),
        migrations.AlterModelTable(
            name='task',
            table='Schedules',
        ),
        migrations.AddField(
            model_name='task',
            name='subplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedules.SubPlan', verbose_name='子计划'),
        ),
    ]
